name: CI/CD pipeline
on:
  push:
    branches:
      - 'master'
      - 'dev'

jobs:
  deploy:
    name: Test Library
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'

      - name: Install dependencies
        run: go mod tidy

      # Sync vendor directory to avoid inconsistencies
      - name: Sync vendor directory
        run: go mod vendor

      - name: Test with the Go CLI
        run: go test